const List<String> expenseCategories = [
  'Inventory / stock purchase',
  'Transportation / freight / logistics',
  'Shop rent / warehouse rent',
  'Salaries & wages',
  'Electricity bill',
  'Internet & phone bills',
  'Packaging materials',
  'Marketing & advertising',
  'Discounts given to customers',
  'GST / taxes / compliance fees',
  'Software subscriptions',
  'Repairs & maintenance',
  'Office supplies',
  'Travel & fuel (general)',
  'Loading / unloading labor',
  'Bank & payment gateway charges',
  'Insurance',
  'Professional fees (CA/legal)',
  'Equipment purchase',
  'Depreciation',
  'Bad debts / credit losses',
  'Staff welfare / training',
  'Licenses & permits',
  'Miscellaneous',
  'Interest on loans / EMIs',
  'Petrol & Diesel',
];
